---
# パッケージインストール-----------------------------------------------------------------------------------------
- name: Install Ubuntu common dev tool packages
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages: "{{ dev_tools }}"
